# fly.toml app configuration file generated for warp-app on 2023-05-21T14:59:26-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "warp-app"
primary_region = "iad"

[[services]]
  protocol = "tcp"
  internal_port = 7761
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
